version: "3.8"
services:
  vending-machine:
    container_name: vending-machine
    restart: always
    build: .
    ports:
      - "7500:8080"
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./data:/data/db